//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TundraCore
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Account
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }

        public override string ToString()
        {
            return Name + " | $" + Balance;
        }
    }
}
