//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TundraCore
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class Goal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal AcruedAmount { get; set; }
        public decimal ContributionAmount { get; set; }
        public bool Accomplished { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime Modified { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(Name + " | ");
            sb.Append(Description);

            return sb.ToString();
        }
    }
}
